extent.reporter.spark.start=true
extent.reporter.spark.out=build/reports/ExtentReport/SparkReport.html
extentreports.cucumber.adapter.screenshot.step.level=true
extentreports.cucumber.adapter.screenshot.storage.mode=base64